import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import config from "@/config/config";
import AppSidebar from "./_components/AppSidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: config.brandName,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  drawers,
}: Readonly<{
  children: React.ReactNode;
  drawers: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        cz-shortcut-listen="true"
      >
        <div className="grid lg:grid-cols-[250px_1fr_400px] min-h-screen p-5 gap-5 font-[family-name:var(--font-geist-sans)]">
            <AppSidebar />
            <main className="rounded-3xl">
              {children}
            </main>
            <div className="cart bg-panel rounded-3xl">
              App cart content display here
            </div>
        </div>
        {drawers}
      </body>
    </html>
  );
}
